import cv2
img = cv2.imread('cat.jpg')
cv2.imshow("Cat Window", img)
cv2.waitKey(0)
cv2.destroyAllWindows()
img = cv2.imread('cat_family.jpg')
cat_face_cascade cv2.CascadeClassifier('haarcascade frontalcatface_extended.xml")
image = cv2.imread(image_path)
cat_face cat_face_cascade.detectMultiScale(image)
cat= Image.open(image_path)
glasses = Image.open('glasses.png')
cat cat.convert("RGBA")
glasses glasses.convert("RGBA")
for (x,y,w,h) in cat_face:
    glasses glasses.resize((w, int(h/3)))
    cat.paste(glasses, box (x, int(y+h/4)), glasses)
    cat.save("cat_with_glasses.png")
    cat_with_glasses = cv2.imread("cat_with_glasses.png")
    cv2.imshow(winname: "Cat_with_glasses", cat_with_glasses)
    cv2.waitKey()